### ISSUE TITLE
OTP Input quick backspaces can leave characters behind

### ISSUE THREAD

**Issue by evoactivity** [universal-ember/ember-primitives#227] opened 2024-02-01 16:14 UTC
Using backspace quickly or holding it can leave characters behind in the input

https://github.com/universal-ember/ember-primitives/assets/83799/c55dc8e9-84c4-4eee-b489-1430a629737e

**Comment by NullVoxPopuli** [comment] 2024-02-03 20:33
This one is hard me to reproduce. I had to bump both my key repeat rate to max, and decrease repeat rate to shortest delay (which makes it almost impossible to type normally lol).

I think what's happening is that input events are firing faster than the frame rate (which is important since requestAnimationFrame is used to help not interfere with default browser event timings

**Comment by NullVoxPopuli** [comment] 2024-02-03 21:50
Thanks for reporting!

Fixed in 0.11.0

https://github.com/universal-ember/ember-primitives/releases/tag/v0.11.0-ember-primitives

**Closed by NullVoxPopuli** 2024-02-03 21:50 UTC
